parameters:
    avro_generator.avro.files:
        controller: 
            filename: 'Controller/{{ entity }}Controller.php'
            template: 'AvroGeneratorBundle:Skeleton/Controller/Avro/Controller.php'
            parameters:
                actions: ['list', 'new', 'edit', 'delete', 'restore', 'import', 'export', 'batchEdit', 'batchDelete', 'batchRestore']
            tags: ['controller', 'crud']
            manipulator:
                service: 'avro_generator.routing.manipulator'
                method: 'updateBundleRouting'
                filename: 'Resources/config/routing.yml'
                setters: 
                    format: 'yml'
        list_view:
            filename: 'Resources/views/{{ entity }}/list.html.twig'
            template: 'AvroGeneratorBundle:Skeleton/Resources/views/Avro/list.html.twig'
            tags: ['view', 'crud']

        new_view:
            filename: 'Resources/views/{{ entity }}/new.html.twig'
            template: 'AvroGeneratorBundle:Skeleton/Resources/views/Avro/new.html.twig'
            tags: ['view', 'crud']

        edit_view:
            filename: 'Resources/views/{{ entity }}/edit.html.twig'
            template: 'AvroGeneratorBundle:Skeleton/Resources/views/Avro/edit.html.twig'
            tags: ['view', 'crud']

        table_view:
            filename: 'Resources/views/{{ entity }}/table.html.twig'
            template: 'AvroGeneratorBundle:Skeleton/Resources/views/Avro/table.html.twig'
            tags: ['view', 'crud']
        searchForm_view:
            filename: 'Resources/views/{{ entity }}/searchForm.html.twig'
            template: 'AvroGeneratorBundle:Skeleton/Resources/views/Avro/searchForm.html.twig'
            tags: ['view', 'crud']

        form_view:
            filename: 'Resources/views/{{ entity }}/form.html.twig'
            template: 'AvroGeneratorBundle:Skeleton/Resources/views/Avro/form.html.twig'
            tags: ['view', 'crud']

        import_view:
            filename: 'Resources/views/{{ entity }}/import.html.twig'
            template: 'AvroGeneratorBundle:Skeleton/Resources/views/Avro/import.html.twig'
            tags: ['view', 'crud', 'import']

        import.handler:
            filename: 'Util/ImportHandler/{{ entity }}ImportHandler.php'
            template: 'AvroGeneratorBundle:Skeleton/Util/ImportHandler/ImportHandler.php'
            tags: ['crud', 'import']
  
        features: 
            filename: 'Features/{{ entity }}.feature'
            template: 'AvroGeneratorBundle:Skeleton/Features/Avro/feature.feature'
            tags: ['test', 'feature']

        entity: 
            filename: 'Entity/{{ entity }}.php'
            template: 'AvroGeneratorBundle:Skeleton/Entity/Entity.php'
            tags: ['entity', 'crud']

        entity_manager: 
            filename: 'Entity/{{ entity }}Manager.php'
            template: 'AvroGeneratorBundle:Skeleton/Entity/EntityManager.php'
            tags: ['entity', 'crud']

        form_type: 
            filename: 'Form/Type/{{ entity }}FormType.php'
            template: 'AvroGeneratorBundle:Skeleton/Form/Type/Avro/FormType.php'
            tags: ['form', 'crud']

        searchForm_type: 
            filename: 'Form/Type/{{ entity }}SearchFormType.php'
            template: 'AvroGeneratorBundle:Skeleton/Form/Type/Avro/SearchFormType.php'
            tags: ['form', 'crud']

        form_handler: 
            filename: 'Form/Handler/{{ entity }}FormHandler.php'
            template: 'AvroGeneratorBundle:Skeleton/Form/Handler/Avro/FormHandler.php'
            tags: ['form', 'crud']

        service_config: 
            filename: 'Resources/config/services/{{ entity_cc }}.yml'
            template: 'AvroGeneratorBundle:Skeleton/Resources/config/services/Avro/service.yml'
            tags: ['service', 'crud']
            manipulator:
                service: 'avro_generator.config.manipulator'
                method: 'addResource'
                filename: 'Resources/config/config.yml'
                setters: 
                    format: 'yml'

    avro_generator.avro.single_files:

    avro_generator.avro.bundle_folders:
        controller:
            path: 'Controller'
        entity:
            path: 'Entity'
        form:
            path: 'Form'
        form_type:
            path: 'Form/Type'
        form_handler:
            path: 'Form/Handler'
        features:
            path: 'Features'
        listener: 
            path: 'Listener'
        resources: 
            path: 'Resources'
        views:
            path: 'Resources/views'
        doc:
            path: 'Resources/doc'
        meta:
            path: 'Resources/meta'
        css:
            path: 'Resources/public/css'
        images:
            path: 'Resources/public/images'
        js:
            path: 'Resources/public/js'
        uploads:
            path: 'Resources/public/uploads'
        translations:
            path: 'Resources/translations'
        config: 
            path: 'Resources/config'
        services:
            path: 'Resources/config/services'

    avro_generator.avro.bundle_files:
        bundle:
            filename: '{{ bundle_name }}.php'
            template: 'AvroGeneratorBundle:Skeleton/Bundle.php'
        configuration:
            filename: 'DependencyInjection/Configuration'
            template: 'AvroGeneratorBundle:Skeleton/DependencyInjection/Configuration.php'
        extension:
            filename: 'DependencyInjection/Extension'
            template: 'AvroGeneratorBundle:Skeleton/DependencyInjection/{{ bundle_vendor }}/{{ bundle_corename | ucFirst }}Extension.php'
        readme:
            filename: 'README.md'
            template: 'AvroGeneratorBundle:Skeleton/README.md'
        layout:
            filename: 'Resources/views/layout.html.twig'
            template: 'AvroGeneratorBundle:Skeleton/Resources/views/Avro/layout.html.twig'
        routing:
            filename: 'Resources/config/routing.yml'
            template: 'AvroGeneratorBundle:Skeleton/Resources/config/routing.yml'
        config:
            filename: 'Resources/config/config.yml'
            template: 'AvroGeneratorBundle:Skeleton/Resources/config/config.yml'
        license:
            filename: 'Resources/meta/LICENSE'
            template: 'AvroGeneratorBundle:Skeleton/Resources/meta/LICENSE'
        git_ignore:
            filename: '.gitignore'
            template: 'AvroGeneratorBundle:Skeleton/gitignore.html.twig'
        composer:
            filename: 'composer.json'
            template: 'AvroGeneratorBundle:composer.json'

