services:
    avro_generator.config.manipulator:
        class: Avro\GeneratorBundle\Manipulator\ConfigManipulator

    avro_generator.routing.manipulator:
        class: Avro\GeneratorBundle\Manipulator\RoutingManipulator
