#{{ entity_cc }}     
services:
    {{ bundle_alias }}.{{ entity_cc }}_manager:
        class: {{ bundle_namespace }}\Entity\{{ entity }}Manager
        arguments: ["@doctrine.orm.entity_manager", {{ bundle_namespace }}\Entity\{{ entity }}, "@security.context"]
        
    {{ bundle_alias }}.{{ entity_cc }}.form.type:
        class: {{ bundle_namespace }}\Form\Type\{{ entity }}FormType
        tags: 
            - { name: form.type, alias: {{ bundle_alias }}_{{ entity_cc }} }
        arguments: ["@security.context"{% if style == 'knockout' %}, "@router"{% endif %}]
       
    {{ bundle_alias }}.{{ entity_cc }}.form:
        factory_method: createNamed 
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: ["@{{ bundle_alias }}.{{ entity_cc }}.form.type", {{ bundle_alias }}_{{ entity_cc }}]
        
    {{ bundle_alias }}.{{ entity_cc }}.form.handler:
        class: {{ bundle_namespace }}\Form\Handler\{{ entity }}FormHandler
        scope: request
        arguments: ["@{{ bundle_alias }}.{{ entity_cc }}.form", "@request", "@{{ bundle_alias }}.{{ entity_cc }}_manager"]

{% if style == 'knockout' %}
    {{ bundle_alias }}.{{ entity_cc }}Search.form.type:
        class: {{ bundle_namespace }}\Form\Type\{{ entity }}SearchFormType
        tags: 
            - { name: form.type, alias: {{ bundle_alias }}_{{ entity_cc }}_search }
        arguments: ["@security.context"]
       
    {{ bundle_alias }}.{{ entity_cc }}Search.form:
        factory_method: createNamed 
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: ["@{{ bundle_alias }}.{{ entity_cc }}Search.form.type", {{ bundle_alias }}_{{ entity_cc }}_search]
{% endif %}

    {{ bundle_alias }}.{{ entity_cc }}_import.handler:
        class: {{ bundle_namespace }}\Import\Handler\{{ entity }}ImportHandler
        scope: request
        arguments: ["@avro_csv.csv.form", "@request", "@avro_csv.reader", "@security.context", "@{{ bundle_alias }}.{{ entity_cc }}_manager"{% for field in fields %}{% if field.type == 'manyToOne' %}, "@{{ field.targetBundleAlias }}.{{ field.targetEntityName }}_manager"{% endif %}{% endfor %}]
