#{{ entityCC }}     
services:
    {{ bundleAlias }}.{{ entityCC }}_manager:
        class: {{ bundleNamespace }}\Entity\{{ entity }}Manager
        arguments: ["@doctrine.orm.entity_manager", {{ bundleNamespace }}\Entity\{{ entity }}, "@security.context"]
        
    {{ bundleAlias }}.{{ entityCC }}.form.type:
        class: {{ bundleNamespace }}\Form\Type\{{ entity }}FormType
        tags: 
            - { name: form.type, alias: {{ bundleAlias }}_{{ entityCC }} }
        arguments: ["@security.context", "@router"]
       
    {{ bundleAlias }}.{{ entityCC }}.form:
        factory_method: createNamed 
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: ["@{{ bundleAlias }}.{{ entityCC }}.form.type", {{ bundleAlias }}_{{ entityCC }}]
        
    {{ bundleAlias }}.{{ entityCC }}.form.handler:
        class: {{ bundleNamespace }}\Form\Handler\{{ entity }}FormHandler
        scope: request
        arguments: ["@{{ bundleAlias }}.{{ entityCC }}.form", "@request", "@{{ bundleAlias }}.{{ entityCC }}_manager"]

    {{ bundleAlias }}.{{ entityCC }}Search.form.type:
        class: {{ bundleNamespace }}\Form\Type\{{ entity }}SearchFormType
        tags: 
            - { name: form.type, alias: {{ bundleAlias }}_{{ entityCC }}_search }
        arguments: ["@security.context", "@router"]
       
    {{ bundleAlias }}.{{ entityCC }}Search.form:
        factory_method: createNamed 
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: ["@{{ bundleAlias }}.{{ entityCC }}Search.form.type", {{ bundleAlias }}_{{ entityCC }}_search]

    {{ bundleAlias }}.{{ entityCC }}_import.handler:
        class: {{ bundleNamespace }}\Import\Handler\{{ entity }}ImportHandler
        scope: request
        arguments: ["@avro_csv.csv.form", "@request", "@avro_csv.reader", "@security.context", "@{{ bundleAlias }}.{{ entityCC }}_manager"{% for field in uniqueManyToOneRelations %}, "@{{ field.targetBundleAlias }}.{{ field.targetEntityName }}_manager"{% endfor %}]
